# Generated by Django 5.0.6 on 2026-05-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_booking_traveler_name_alter_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='image_url',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
