# Generated by Django 6.0.4 on 2026-05-10 13:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_booking_num_persons_alter_booking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(default=core.models.get_ist_time),
        ),
    ]
