# Generated by Django 6.0.4 on 2026-05-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_adults',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
