# Generated by Django 6.0.3 on 2026-05-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_booking_num_adults_booking_num_children'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
